    echo -e "\e[1;36m"
    echo "Countries Code Info"
    echo "================================================================================================"
    echo -e "\e[0;36m"
    echo "Country Code ==> Country Name"
    echo "-----------------------------"
    echo "AD"" ==> ""Andorra"
    echo "AE"" ==> ""United Arab Emirates"
    echo "AF"" ==> ""Afghanistan"
    echo "AG"" ==> ""Antigua and Barbuda"
    echo "AI"" ==> ""Anguilla"
    echo "AL"" ==> ""Albania"
    echo "AM"" ==> ""Armenia"
    echo "AO"" ==> ""Angola"
    echo "AQ"" ==> ""Antarctica"
    echo "AR"" ==> ""Argentina"
    echo "AS"" ==> ""American Samoa"
    echo "AT"" ==> ""Austria"
    echo "AU"" ==> ""Australia"
    echo "AW"" ==> ""Aruba"
    echo "AX"" ==> ""Aland Islands"
    echo "AZ"" ==> ""Azerbaijan"
    echo "BA"" ==> ""Bosnia and Herzegovina"
    echo "BB"" ==> ""Barbados"
    echo "BD"" ==> ""Bangladesh"
    echo "BE"" ==> ""Belgium"
    echo "BF"" ==> ""Burkina Faso"
    echo "BG"" ==> ""Bulgaria"
    echo "BH"" ==> ""Bahrain"
    echo "BI"" ==> ""Burundi"
    echo "BJ"" ==> ""Benin"
    echo "BL"" ==> ""Saint Barthelemy"
    echo "BM"" ==> ""Bermuda"
    echo "BN"" ==> ""Brunei"
    echo "BO"" ==> ""Bolivia"
    echo "BQ"" ==> ""Bonaire, Saint Eustatius and Saba"
    echo "BR"" ==> ""Brazil"
    echo "BS"" ==> ""Bahamas"
    echo "BT"" ==> ""Bhutan"
    echo "BV"" ==> ""Bouvet Island"
    echo "BW"" ==> ""Botswana"
    echo "BY"" ==> ""Belarus"
    echo "BZ"" ==> ""Belize"
    echo "CA"" ==> ""Canada"
    echo "CC"" ==> ""Cocos Islands"
    echo "CD"" ==> ""Democratic Republic of the Congo"
    echo "CF"" ==> ""Central African Republic"
    echo "CG"" ==> ""Republic of the Congo"
    echo "CH"" ==> ""Switzerland"
    echo "CI"" ==> ""Ivory Coast"
    echo "CK"" ==> ""Cook Islands"
    echo "CL"" ==> ""Chile"
    echo "CM"" ==> ""Cameroon"
    echo "CN"" ==> ""China"
    echo "CO"" ==> ""Colombia"
    echo "CR"" ==> ""Costa Rica"
    echo "CU"" ==> ""Cuba"
    echo "CV"" ==> ""Cape Verde"
    echo "CW"" ==> ""Curacao"
    echo "CX"" ==> ""Christmas Island"
    echo "CY"" ==> ""Cyprus"
    echo "CZ"" ==> ""Czech Republic"
    echo "DE"" ==> ""Germany"
    echo "DJ"" ==> ""Djibouti"
    echo "DK"" ==> ""Denmark"
    echo "DM"" ==> ""Dominica"
    echo "DO"" ==> ""Dominican Republic"
    echo "DZ"" ==> ""Algeria"
    echo "EC"" ==> ""Ecuador"
    echo "EE"" ==> ""Estonia"
    echo "EG"" ==> ""Egypt"
    echo "EH"" ==> ""Western Sahara"
    echo "ER"" ==> ""Eritrea"
    echo "ES"" ==> ""Spain"
    echo "ET"" ==> ""Ethiopia"
    echo "FI"" ==> ""Finland"
    echo "FJ"" ==> ""Fiji"
    echo "FK"" ==> ""Falkland Islands"
    echo "FM"" ==> ""Micronesia"
    echo "FO"" ==> ""Faroe Islands"
    echo "FR"" ==> ""France"
    echo "GA"" ==> ""Gabon"
    echo "GB"" ==> ""United Kingdom"
    echo "GD"" ==> ""Grenada"
    echo "GE"" ==> ""Georgia"
    echo "GF"" ==> ""French Guiana"
    echo "GG"" ==> ""Guernsey"
    echo "GH"" ==> ""Ghana"
    echo "GI"" ==> ""Gibraltar"
    echo "GL"" ==> ""Greenland"
    echo "GM"" ==> ""Gambia"
    echo "GN"" ==> ""Guinea"
    echo "GP"" ==> ""Guadeloupe"
    echo "GQ"" ==> ""Equatorial Guinea"
    echo "GR"" ==> ""Greece"
    echo "GS"" ==> ""South Georgia and the South Sandwich Islands"
    echo "GT"" ==> ""Guatemala"
    echo "GU"" ==> ""Guam"
    echo "GW"" ==> ""Guinea-Bissau"
    echo "GY"" ==> ""Guyana"
    echo "HK"" ==> ""Hong Kong"
    echo "HM"" ==> ""Heard Island and McDonald Islands"
    echo "HN"" ==> ""Honduras"
    echo "HR"" ==> ""Croatia"
    echo "HT"" ==> ""Haiti"
    echo "HU"" ==> ""Hungary"
    echo "ID"" ==> ""Indonesia"
    echo "IE"" ==> ""Ireland"
    echo "IL"" ==> ""Israel"
    echo "IM"" ==> ""Isle of Man"
    echo "IN"" ==> ""India"
    echo "IO"" ==> ""British Indian Ocean Territory"
    echo "IQ"" ==> ""Iraq"
    echo "IR"" ==> ""Iran"
    echo "IS"" ==> ""Iceland"
    echo "IT"" ==> ""Italy"
    echo "JE"" ==> ""Jersey"
    echo "JM"" ==> ""Jamaica"
    echo "JO"" ==> ""Jordan"
    echo "JP"" ==> ""Japan"
    echo "KE"" ==> ""Kenya"
    echo "KG"" ==> ""Kyrgyzstan"
    echo "KH"" ==> ""Cambodia"
    echo "KI"" ==> ""Kiribati"
    echo "KM"" ==> ""Comoros"
    echo "KN"" ==> ""Saint Kitts and Nevis"
    echo "KP"" ==> ""North Korea"
    echo "KR"" ==> ""South Korea"
    echo "XK"" ==> ""Kosovo"
    echo "KW"" ==> ""Kuwait"
    echo "KY"" ==> ""Cayman Islands"
    echo "KZ"" ==> ""Kazakhstan"
    echo "LA"" ==> ""Laos"
    echo "LB"" ==> ""Lebanon"
    echo "LC"" ==> ""Saint Lucia"
    echo "LI"" ==> ""Liechtenstein"
    echo "LK"" ==> ""Sri Lanka"
    echo "LR"" ==> ""Liberia"
    echo "LS"" ==> ""Lesotho"
    echo "LT"" ==> ""Lithuania"
    echo "LU"" ==> ""Luxembourg"
    echo "LV"" ==> ""Latvia"
    echo "LY"" ==> ""Libya"
    echo "MA"" ==> ""Morocco"
    echo "MC"" ==> ""Monaco"
    echo "MD"" ==> ""Moldova"
    echo "ME"" ==> ""Montenegro"
    echo "MF"" ==> ""Saint Martin"
    echo "MG"" ==> ""Madagascar"
    echo "MH"" ==> ""Marshall Islands"
    echo "MK"" ==> ""Macedonia"
    echo "ML"" ==> ""Mali"
    echo "MM"" ==> ""Myanmar"
    echo "MN"" ==> ""Mongolia"
    echo "MO"" ==> ""Macao"
    echo "MP"" ==> ""Northern Mariana Islands"
    echo "MQ"" ==> ""Martinique"
    echo "MR"" ==> ""Mauritania"
    echo "MS"" ==> ""Montserrat"
    echo "MT"" ==> ""Malta"
    echo "MU"" ==> ""Mauritius"
    echo "MV"" ==> ""Maldives"
    echo "MW"" ==> ""Malawi"
    echo "MX"" ==> ""Mexico"
    echo "MY"" ==> ""Malaysia"
    echo "MZ"" ==> ""Mozambique"
    echo "NA"" ==> ""Namibia"
    echo "NC"" ==> ""New Caledonia"
    echo "NE"" ==> ""Niger"
    echo "NF"" ==> ""Norfolk Island"
    echo "NG"" ==> ""Nigeria"
    echo "NI"" ==> ""Nicaragua"
    echo "NL"" ==> ""Netherlands"
    echo "NO"" ==> ""Norway"
    echo "NP"" ==> ""Nepal"
    echo "NR"" ==> ""Nauru"
    echo "NU"" ==> ""Niue"
    echo "NZ"" ==> ""New Zealand"
    echo "OM"" ==> ""Oman"
    echo "PA"" ==> ""Panama"
    echo "PE"" ==> ""Peru"
    echo "PF"" ==> ""French Polynesia"
    echo "PG"" ==> ""Papua New Guinea"
    echo "PH"" ==> ""Philippines"
    echo "PK"" ==> ""Pakistan"
    echo "PL"" ==> ""Poland"
    echo "PM"" ==> ""Saint Pierre and Miquelon"
    echo "PN"" ==> ""Pitcairn"
    echo "PR"" ==> ""Puerto Rico"
    echo "PS"" ==> ""Palestinian Territory"
    echo "PT"" ==> ""Portugal"
    echo "PW"" ==> ""Palau"
    echo "PY"" ==> ""Paraguay"
    echo "QA"" ==> ""Qatar"
    echo "RE"" ==> ""Reunion"
    echo "RO"" ==> ""Romania"
    echo "RS"" ==> ""Serbia"
    echo "RU"" ==> ""Russia"
    echo "RW"" ==> ""Rwanda"
    echo "SA"" ==> ""Saudi Arabia"
    echo "SB"" ==> ""Solomon Islands"
    echo "SC"" ==> ""Seychelles"
    echo "SD"" ==> ""Sudan"
    echo "SS"" ==> ""South Sudan"
    echo "SE"" ==> ""Sweden"
    echo "SG"" ==> ""Singapore"
    echo "SH"" ==> ""Saint Helena"
    echo "SI"" ==> ""Slovenia"
    echo "SJ"" ==> ""Svalbard and Jan Mayen"
    echo "SK"" ==> ""Slovakia"
    echo "SL"" ==> ""Sierra Leone"
    echo "SM"" ==> ""San Marino"
    echo "SN"" ==> ""Senegal"
    echo "SO"" ==> ""Somalia"
    echo "SR"" ==> ""Suriname"
    echo "ST"" ==> ""Sao Tome and Principe"
    echo "SV"" ==> ""El Salvador"
    echo "SX"" ==> ""Sint Maarten"
    echo "SY"" ==> ""Syria"
    echo "SZ"" ==> ""Swaziland"
    echo "TC"" ==> ""Turks and Caicos Islands"
    echo "TD"" ==> ""Chad"
    echo "TF"" ==> ""French Southern Territories"
    echo "TG"" ==> ""Togo"
    echo "TH"" ==> ""Thailand"
    echo "TJ"" ==> ""Tajikistan"
    echo "TK"" ==> ""Tokelau"
    echo "TL"" ==> ""East Timor"
    echo "TM"" ==> ""Turkmenistan"
    echo "TN"" ==> ""Tunisia"
    echo "TO"" ==> ""Tonga"
    echo "TR"" ==> ""Turkey"
    echo "TT"" ==> ""Trinidad and Tobago"
    echo "TV"" ==> ""Tuvalu"
    echo "TW"" ==> ""Taiwan"
    echo "TZ"" ==> ""Tanzania"
    echo "UA"" ==> ""Ukraine"
    echo "UG"" ==> ""Uganda"
    echo "UM"" ==> ""United States Minor Outlying Islands"
    echo "US"" ==> ""United States"
    echo "UY"" ==> ""Uruguay"
    echo "UZ"" ==> ""Uzbekistan"
    echo "VA"" ==> ""Vatican"
    echo "VC"" ==> ""Saint Vincent and the Grenadines"
    echo "VE"" ==> ""Venezuela"
    echo "VG"" ==> ""British Virgin Islands"
    echo "VI"" ==> ""U.S. Virgin Islands"
    echo "VN"" ==> ""Vietnam"
    echo "VU"" ==> ""Vanuatu"
    echo "WF"" ==> ""Wallis and Futuna"
    echo "WS"" ==> ""Samoa"
    echo "YE"" ==> ""Yemen"
    echo "YT"" ==> ""Mayotte"
    echo "ZA"" ==> ""South Africa"
    echo "ZM"" ==> ""Zambia"
    echo "ZW"" ==> ""Zimbabwe"
    echo "CS"" ==> ""Serbia and Montenegro"
    echo "AN"" ==> ""Netherlands Antilles"
    echo -e "\e[1;36m"
    echo "================================================================================================"
    echo -e "\e[0m"