    echo -e "\e[1;36m"
    echo "Languages Code Info"
    echo "================================================================================================"
    echo -e "\e[0;36m"
    echo "Language Code ==> Language Name"
    echo "-----------------------------"
    echo "de"" ==> ""German"
    echo "en"" ==> ""English"
    echo "es"" ==> ""Spanish"
    echo "fr"" ==> ""French"
    echo "ja"" ==> ""Japanese"
    echo "pt"" ==> ""Portuguese"
    echo "ru"" ==> ""Russian"
    echo "zh"" ==> ""Chinese"
    echo -e "\e[1;36m"
    echo "================================================================================================"
    echo -e "\e[0m"